name: personal-website # Name of project

on: # Run the workflow on each tag push
  push:
    tags:
      - v*

jobs:
  Deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          php-version: '7.4'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: List all files to see which branch were working on
        run: ls -la
      - name: Updating composer.lock file
        run: composer update --lock
      - name: Installing dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate project key
        run: php artisan key:generate
      - name: Change directory permissions
        run: chmod -R 775 storage bootstrap/cache
      - name: Database Migrate
        run: php artisan migrate

