name: personal-website # Name of project

on: # Run the workflow on each tag push
  push:
    tags:
      - v*

jobs:
  Copy-env:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
  Installing-dependencies:
    name: Installing dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        with:
          php-version: '7.4'
      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  Generating_key:
    name: Generating project key
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generating project key
        with:
          php-version: '7.4'
      - run: php artisan key:generate
  Changing_file_permissions:
    name: Changing file permissions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Changing file permissions
      - run: chmod -R 775 storage bootstrap/cache
  Migration_database:
    name: Migrating Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Migrating database
        with:
          php-version: '7.4'
      - run: php artisan migrate



