name: personal-website # Name of project

on: # Run the workflow on each tag push
  push:
    tags:
      - v*

jobs:
  Deploy: # Deploy script to production to finalize it
    name: Deploy to production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /var/www/html/
            ls -la
            php artisan down
            git pull origin master
            composer install —optimize-autoloader —no-dev
            npm install
            npm run production
            php artisan migrate
            php artisan schedule:run
            php artisan cache:clear
            php artisan up


