name: personal-website # Name of project

on: # Run the workflow on each tag push
  push:
    tags:
      - v*

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4' ]
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd /var/www/html/
            ls -la


