name: personal-website # Name of project

on: # Run the workflow on each tag push
  push:
    tags:
      - v*

jobs:
  Deployment:
    name: Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]
        php-versions: [ '7.2', '7.3', '7.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Check PHP Version
        run: php -v
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: List all files to see which branch were working on
        run: ls -la
      - name: Updating composer.lock file
        run: composer update --lock
      - name: Installing dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate project key
        run: php artisan key:generate
      - name: Change directory permissions
        run: chmod -R 775 storage bootstrap/cache
      - name: Database Migrate
        run: php artisan migrate

