name: personal-website # Name of project

on: # Run the workflow on each tag push
  push:
    tags:
      - v*

jobs:
  Deployment:
    name: Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4' ]
    steps:
      - name: Run actions/checkout@v2
        uses: actions/checkout@v2

      - name: Setup PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Prepare Laravel Application
        run: cp .env.example .env
             php artisan key:generate

      - name: Updating composer.lock file
        run: composer update --lock

      - name: Installing dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run npm install
        run: npm install

      - name: Change directory permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Database Migrate
        run: php artisan migrate

